## [Grant of Rights by HOFV]{.underline}. HOFV grants to Sponsor a nonexclusive, nontransferable, royalty free license to use the marks set forth on [[Exhibit C](#exhibit-c)]{.underline} ("[HOFV's Marks]{.underline}") in the United States during the Term in connection with, but only to the extent necessary to provide for, the Sponsorship Rights. All uses of HOFV's Marks shall inure solely to HOFV's benefit. On termination or expiration of this Agreement, Sponsor shall cease all use of HOFV's Marks as soon as practicable, but in any event within thirty (30) days unless the particular media which has been approved requires a longer lead time, but in no event longer than ninety (90) days. Sponsor shall have no right to assign any right granted hereunder to use HOFV's Marks or any other Sponsorship Rights granted hereunder, to any third party or co-brand, or the HOFV's Marks in an express or implied connection or association with any third parties. {#intellectual-property-rights:grant-of-rights}
