### [Effect of Termination]{.underline}. In the event of a termination by either Party pursuant to this `r ref("#termination-available-remedies")`, Sponsor shall return to HOFV all tickets, if any, issued to Sponsor pursuant to this Agreement. In addition, in the event of a termination by either Party for any reason (including at the expiration of the Term), the Parties agree that all representations and warranties made under this Agreement in `r ref("representation-and-warranties")` and the indemnification provisions set forth in `r ref("#indemnification")` for any claims, demands, causes of action, suits or judgments by third parties or losses, liabilities, costs or expenses which may arise on or before the effective date of termination shall survive. In the event of expiration or termination of this Agreement, any licenses granted hereunder shall immediately terminate. The Parties agree that any outstanding payment obligations in `r ref("fees", "production-execution")`, as well as `r ref("intellectual-property-rights:reservation-of-rights", "termination-available-remedies", "dispute-resolution", "miscellaneous:governing-law")`, shall survive any such expiration or termination of this Agreement. {#termination-available-remedies:remedies-effect-of-termination:effect-of-termination}
