## [By HOFV]{.underline}. HOFV agrees to defend, indemnify and hold harmless Sponsor and its shareholders, partners, officers, directors, employees, successors, assigns, representatives, servants and agents (collectively, the "[Sponsor Indemnified Persons]{.underline}") from and against, and HOFV waives any claim for contribution or indemnity against any Sponsor Indemnified Person with respect to, any and all Indemnified Losses resulting from or arising out of (i) the use or display by Sponsor of HOFV's Marks pursuant to any licenses granted herein; or (ii) any breach by HOFV of its representations and/or warranties under this Agreement, as well as any breach of any confidentiality obligations under this Agreement; or (iii) any and all alleged grossly negligent or willful acts or fraud of HOFV, its affiliates and their respective officers, directors, partners, subcontractors, employees, servants and agents; or (iv) the subject matter, content or copy contained in any material, signage or intellectual property furnished by HOFV in accordance with this Agreement, including any and all claims for infringement of trademark rights, copyrights, testimonials, rights of publicity, or the rights to use names, likenesses, slogans, photographs or patents (except for claims arising solely from use of Sponsor's Marks); or (v) the alleged failure by HOFV or of its affiliates to comply with any governmental and/or other laws, statutes, ordinances, rules, and/or regulations. {#indemnification:by-hofv}
