## [By Sponsor]{.underline}. Sponsor agrees to defend, indemnify and hold harmless HOFV and its affiliates and their respective shareholders, partners, officers, directors, employees, successors, assigns, representatives, servants and agents (collectively with HOFV and its respective affiliates, the "[HOFV Indemnified Persons]{.underline}") from and against, and Sponsor waives any claim for contribution or indemnity against any HOFV Indemnified Person with respect to, any and all claims, suits, actions, claims, monetary damages, losses, liabilities, fines, fees, penalties, costs and expenses ("[Losses]{.underline}"), and all reasonable attorneys' fees and expenses, including court costs and expert witness fees and costs, incurred in connection with Losses and/or enforcement of this Agreement ("[Indemnified Losses]{.underline}") resulting from or arising out of (i) the use or display by HOFV of Sponsor's Marks pursuant to any licenses granted herein; or (ii) the manufacture, promotion, advertising, distribution and sale of any services or products by Sponsor; or (iii) any breach by Sponsor of its representations and/or warranties under this Agreement, as well as any breach of the confidentiality obligations under this Agreement; or (iv) any and all alleged willful or grossly negligent acts or fraud of Sponsor, its affiliates and their respective officers, directors, partners, subcontractors, employees, servants and agents; or (v) the subject matter, content or copy contained in any advertising material, promotional material, signage or intellectual property furnished by Sponsor in accordance with this Agreement, including any and all claims for infringement of trademark rights, copyrights, testimonials, rights of publicity, or the rights to use names, likenesses, slogans, photographs or patents (other than arising solely from use of HOFV's Marks); or (vi) the alleged failure by Sponsor or of its affiliates to comply with any governmental and/or other laws, statutes, ordinances, rules, and/or regulations. {#indemnification:by-sponsor}
