## [Procedure for Indemnification]{.underline}. Each Party seeking to be reimbursed, indemnified, defended, and held harmless under `r ref("#indemnification:by-sponsor")` or `r ref("#indemnification:by-hofv")` (each, an "[Indemnitee]{.underline}") shall (a) provide the party obligated to indemnify such Indemnitee (the "[Indemnitor]{.underline}") with prompt, written notice of any claim, suit, demand, or other action for which such Indemnitee seeks to be reimbursed, indemnified, defended, and held harmless (each, a "[Claim]{.underline}"), which notice shall include a reasonable identification of the alleged facts giving rise to such Claim; (b) grant such party reasonable authority and control over the defense and settlement of any such Claim; and (c) reasonably cooperate with such party and its agents in defense of any such Claim, at the Indemnitor's expense. Each Indemnitee shall have the right to participate in the defense of any Claim for which Indemnitee seeks to be reimbursed, indemnified, defended, or held harmless, by using attorneys of such Indemnitee's choice, at such Indemnitee's expense. Any settlement of a Claim for which any Indemnitee seeks to be reimbursed, indemnified, defended, or held harmless under this `r ref("#indemnification")` shall be subject to the prior written approval of such Indemnitee, which approval shall not be unreasonably withheld, conditioned, or delayed. {#indemnification:procedure-for-indemnification}
