### Sponsor grants to HOFV a nonexclusive, nontransferable, royalty free license to use the marks set forth on [[Exhibit D](#exhibit-d)]{.underline} ("[Sponsor's Marks]{.underline}") in the United States during the Term in connection with, but only to the extent necessary to provide for, the Sponsorship Rights and the advertising and promotion of the Village, including, without limitation, any musical, athletic or other live performance events at the Village. HOFV shall have the right to identify Sponsor as a sponsor of the Village and to use the Sponsor's Marks in connection with television, radio, Internet, VOD, and print advertising of the Village and events held at the Village. Sponsor acknowledges that it is familiar with HOFV's events and services and agrees that HOFV may use Sponsor's Marks provided that HOFV's events and services are of similar or better quality to the events and services that HOFV offers as of the Effective Date. On termination or expiration of this Agreement, HOFV shall cease all use of Sponsor's Marks as soon as practicable, but in any event within thirty (30) days unless the particular media which has been approved requires a longer lead time, but in no event longer than ninety (90) days. {#intellectual-property-rights:grant-of-rights-by-sponsor:royalty-free-license}
