### [Other]{.underline}. Except as otherwise set forth in `r ref("#miscellaneous:force-majuere:fire-or-other-damage")` hereof, neither Party shall be liable or responsible for any failure to perform its obligations hereunder, which failure is caused or brought about in any manner beyond the control of such Party, including, but not limited to, the breakdown or failure of apparatus, equipment, or machinery employed in its supply of said services, any temporary stoppage for the repair, improvement or enlargement thereof, or any other act or condition beyond its reasonable control, other than such Party's inability to perform payment obligations. Notwithstanding the foregoing, in the event traffic at the Village is materially adversely impacted by government closures or as a result of travel limitations due to executive order, the Parties agree to meet and confer regarding potential adjustments to the Sponsorship Fee or an equitable extension of the Term. {#miscellaneous:force-majuere:repairs}
