## [Confidentiality]{.underline}. For a period of eighteen (18) months after termination of this Agreement, the parties hereto agree to maintain in confidence the terms and conditions of this Agreement and any non-public information and/or trade secrets received rom the other party in the course of performing the obligations set forth in this Agreement that is either marked as "Confidential" or which, under the circumstances, ought to be treated as confidential (collectively, "**Confidential Information**") (except with respect to their owners, lenders and advisors, each of whom is to be made aware of and instructed to comply with this confidentiality provision) unless the proposed disclosure is authorized in advance by the other Party or is otherwise required by law. In the event that either Party or any of its representatives becomes legally compelled to disclose Confidential Information, such Party shall, to the extent reasonably practicable, provide the other Party with prompt written notice before such disclosure, sufficient to enable such other Party either to seek a protective order, at its expense, or another appropriate remedy preventing or prohibiting such disclosure or to waive compliance with the provisions of this `r ref("#miscellaneous:confidentiality")`, or both. Notwithstanding the above, "Confidential Information" will not include any information that (a) is publicly available at the time of disclosure or subsequently becomes publicly available through no fault of the receiving party; (b) became known to the receiving party prior to the disclosing party's disclosure of such information to the receiving party; (c) became known to the receiving party from a source other than the disclosing party other than by breach of an obligation of confidentiality owed to the disclosing party; or (d) is independently developed by the receiving party. {#miscellaneous:confidentiality}
